{% set name = "jupyter_server" %}
{% set version = "1.0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58913ab2dac9dd85d5a00d71a4735f745b1fc823217a60eaad1881d0837380b6

build:
  noarch: python
  number: 1
  script:
    - {{ PYTHON }} -c "__import__('shutil').rmtree('tests')"
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main
    - jupyter-bundlerextension = jupyter_server.bundlerextensions:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipython_genutils
    - jinja2
    - jupyter_core >=4.4.0
    - jupyter_client >=6.1.1
    - nbconvert
    - nbformat
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.3
    - tornado >=5.0
    - traitlets >=4.2.1
    - prometheus_client
    # presumably this will always be provided by jupyter_core, saving much CI
    # - pywin32 >=1.0  # [win]

test:
  commands:
    - jupyter server -h
  imports:
    - jupyter_server

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Jupyter Server
  description: The Jupyter Server provides the backend for Jupyter web applications such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server
  doc_url: https://jupyter-server.readthedocs.io
  doc_source_url: https://github.com/jupyter-server/jupyter_server/tree/{{ version }}/docs/source

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
